### ISSUE TITLE
Switch to MIT License

### ISSUE THREAD

**Issue by aqw** [aqw/pigskin#5]
Some projects will be put off by the LGPL license. To minimize barriers for adoption, it would be helpful to relicense this library under the MIT license.

If you contributed to the xbmc-gamepass project, it would be great if you could take the time to respond to this issue and state whether (or not) you'd be willing to license your previous contributions under the MIT license.

It may not be possible to get in contact with everyone in order to do this, but it's worth a try.

Contributors we need approval from:

- [X] @aqw
- [X] @BaumSchorle 
- [x] @emilsvennesson 
- [x] @divingmule 
- [x] @eriksoderblom 
- [x] @rva87 
- [x] @kaileu 
- [ ] @DAhlstrom 
- [x] @timewasted

**Comment by BaumSchorle** [comment]
I am OK with it 👍

**Comment by aqw** [comment]
@BaumSchorle Thanks! I've marked that down.

It's great to hear from you. Hope life is treating you well. :-)

---Alex

**Comment by BaumSchorle** [comment]
@aqw Life is spoiling me at the moment, family is growing which is the best thing ever, sadly it means I have little to no time for this project.

**Comment by rva87** [comment]
@aqw Fine with me

**Comment by aqw** [comment]
@rva87 Thanks! Marked.

**Comment by aqw** [comment]
@BaumSchorle Congrats on the new members of your family! Real life does have a weird way of getting in the way of projects... ;-)

**Comment by timewasted** [comment]
I'm fine with the change.

**Comment by aqw** [comment]
@timewasted Great! Thanks for responding. :-) Marked.

**Comment by kaileu** [comment]
I am fine with it.

Mit freundlichen Grüßen
Kai Leutner

**Comment by aqw** [comment]
@kaileu Great! Thanks for the response. Marked.

**Comment by divingmule** [comment]
@aqw it's for sure fine with me 👍

**Comment by aqw** [comment]
@divingmule @emilsvennesson Fantastic, thanks for the responses. Marked.

@divingmule Great to hear from you. It's been a long time since we started this addon together. Thanks for helping to make it happen, and I hope life is treating you well. :-)

**Comment by eriksoderblom** [comment]
The change is fine with me

**Comment by aqw** [comment]
@eriksoderblom Fantastic. Thanks! Marked.
